In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['font.family'] = 'AppleGothic'
df = pd.read_csv('aihub (1).csv', encoding='cp949')

In [3]:
df.columns

Index(['기준년월', '가명 식별자', '업종(중분류)', '유동자산', '비유동자산', '현금', '자산총계', '자산총계(전기)',
       '유동부채', '단기차입금', '부채총계', '자기자본(납입자본금)', '이익잉여금', '매출액', '전기매출액', '영업손익',
       '당기순이익', '현금흐름', '영업활동현금흐름', '재무활동현금흐름', '이자비용', '이자보상배율', 'EBIT',
       'EBITDA', '총자산증가율', '부채비율', '유동비율', '매출액증가율', '영업이익율', '당기순이익율',
       '자기자본이익률(ROE)', '총자산순이익률', '유동자산증가율', '유형자산증가율', '매출총이익율', '영업이익증가율',
       '당기순이익증가율', 'EBITDA증가율', '차입금/EBITDA', 'EBITDA/금융비용',
       '기준년월 시점 대출연체 과목수', '기준년월 시점 3개월내 대출연체 유지 과목수(연체대출금 상환 포함)',
       '기준년월 시점 6개월내 대출연체 유지 과목수(연체대출금 상환 포함)',
       '기준년월 시점 1년내 대출연체 유지 과목수(연체대출금 상환 포함)',
       '기준년월 시점 3년내 대출연체 유지 과목수(연체대출금 상환 포함)',
       '기준년월 시점 연체일수가 30일 이상 된 대출연체 유지 과목수(연체대출금 상환 포함)',
       '기준년월 시점 신용도판단정보 및 공공정보 (한국신용정보원) 발생건수(해제 제외)',
       '기준년월 시점 공공정보 (한국신용정보원) 유지건수(해제 제외)',
       '기준년월 시점 신용도판단정보 및 공공정보 (한국신용정보원) 최근 해제일자로 부터 경과일수',
       '기준일로부터 향후 1년내 부도, 기업회생, 90일이상 금융연체, 대지급 등 발생여부(신용정보원 기준). 1: 향후1년내 부도발생, 0: 향후1년내 부도미발생',
       '업종(대분류)', '시도명', '시군구명'

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 124989 entries, 0 to 124988
Data columns (total 53 columns):
 #   Column                                                                                   Non-Null Count   Dtype  
---  ------                                                                                   --------------   -----  
 0   기준년월                                                                                     124989 non-null  int64  
 1   가명 식별자                                                                                   124989 non-null  int64  
 2   업종(중분류)                                                                                  124989 non-null  object 
 3   유동자산                                                                                     124989 non-null  int64  
 4   비유동자산                                                                                    124989 non-null  int64  
 5   현금                                                 

In [5]:
np.unique(df['기준일로부터 향후 1년내 부도, 기업회생, 90일이상 금융연체, 대지급 등 발생여부(신용정보원 기준). 1: 향후1년내 부도발생, 0: 향후1년내 부도미발생'], return_counts=True)

(array([0, 1]), array([123163,   1826]))

In [6]:
l = []
for i in df['업종(대분류)']:
    if '건설' in i:
        l.append(i)

In [7]:
len(l)

15653

In [9]:
df_건설 = df[df['업종(대분류)'].str.contains('건설', na=False)]

In [12]:
np.unique(df_건설['기준일로부터 향후 1년내 부도, 기업회생, 90일이상 금융연체, 대지급 등 발생여부(신용정보원 기준). 1: 향후1년내 부도발생, 0: 향후1년내 부도미발생'], return_counts=True)

(array([0, 1]), array([15445,   208]))

In [15]:
np.unique(df_건설['기준년월 시점 6개월내 대출연체 유지 과목수(연체대출금 상환 포함)'], return_counts=True)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 13, 43]),
 array([15473,   104,    41,     6,     9,     7,     2,     3,     3,
            1,     2,     1,     1]))

In [17]:
df_건설.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15653 entries, 13 to 124943
Data columns (total 53 columns):
 #   Column                                                                                   Non-Null Count  Dtype  
---  ------                                                                                   --------------  -----  
 0   기준년월                                                                                     15653 non-null  int64  
 1   가명 식별자                                                                                   15653 non-null  int64  
 2   업종(중분류)                                                                                  15653 non-null  object 
 3   유동자산                                                                                     15653 non-null  int64  
 4   비유동자산                                                                                    15653 non-null  int64  
 5   현금                                                             

In [18]:
# 1-1. 결측치 확인
missing_info = df_건설.isnull().sum()
missing_info = missing_info[missing_info > 0].sort_values(ascending=False)
print("📌 결측치 있는 컬럼:\n", missing_info)

# 1-2. 고정값(유니크값 1개) 확인
unique_counts = df_건설.nunique()
fixed_columns = unique_counts[unique_counts == 1]
print("📌 고정값 컬럼:\n", fixed_columns)

📌 결측치 있는 컬럼:
 Series([], dtype: int64)
📌 고정값 컬럼:
 기준년월       1
업종(대분류)    1
dtype: int64


In [19]:
# 2-1. 수치형 피처만 추출
numeric_cols = df_건설.select_dtypes(include=['int64', 'float64']).drop(columns=['가명 식별자', '기준년월'])

# 2-2. 타겟(y) 지정
y = df_건설['기준일로부터 향후 1년내 부도, 기업회생, 90일이상 금융연체, 대지급 등 발생여부(신용정보원 기준). 1: 향후1년내 부도발생, 0: 향후1년내 부도미발생']

# 2-3. 상관관계 계산
correlations = numeric_cols.corrwith(y).sort_values(key=abs, ascending=False)
print("📌 타겟(y)과 상관관계 높은 피처 TOP 15:\n", correlations.head(15))


📌 타겟(y)과 상관관계 높은 피처 TOP 15:
 기준일로부터 향후 1년내 부도, 기업회생, 90일이상 금융연체, 대지급 등 발생여부(신용정보원 기준). 1: 향후1년내 부도발생, 0: 향후1년내 부도미발생    1.000000
기준년월 시점 신용도판단정보 및 공공정보 (한국신용정보원) 최근 해제일자로 부터 경과일수                                         -0.071204
기준년월 시점 공공정보 (한국신용정보원) 유지건수(해제 제외)                                                         0.068821
기준년월 시점 3개월내 대출연체 유지 과목수(연체대출금 상환 포함)                                                      0.050360
기준년월 시점 1년내 대출연체 유지 과목수(연체대출금 상환 포함)                                                       0.043021
기준년월 시점 연체일수가 30일 이상 된 대출연체 유지 과목수(연체대출금 상환 포함)                                            0.041034
기준년월 시점 신용도판단정보 및 공공정보 (한국신용정보원) 발생건수(해제 제외)                                               0.039003
기준년월 시점 3년내 대출연체 유지 과목수(연체대출금 상환 포함)                                                       0.036576
기준년월 시점 대출연체 과목수                                                                           0.029712
기준년월 시점 6개월내 대출연체 유지 과목수(연체대출금 상환 포함)                                  

/opt/anaconda3/lib/python3.12/site-packages/numpy/lib/function_base.py:2742: RuntimeWarning: invalid value encountered in subtract
  X -= avg[:, None]


In [22]:
# 피처 리스트
selected_features = [
    '기준년월 시점 신용도판단정보 및 공공정보 (한국신용정보원) 최근 해제일자로 부터 경과일수',
    '기준년월 시점 공공정보 (한국신용정보원) 유지건수(해제 제외)',
    '기준년월 시점 3개월내 대출연체 유지 과목수(연체대출금 상환 포함)',
    '기준년월 시점 1년내 대출연체 유지 과목수(연체대출금 상환 포함)',
    '기준년월 시점 연체일수가 30일 이상 된 대출연체 유지 과목수(연체대출금 상환 포함)',
    '기준년월 시점 신용도판단정보 및 공공정보 (한국신용정보원) 발생건수(해제 제외)',
    '기준년월 시점 3년내 대출연체 유지 과목수(연체대출금 상환 포함)',
    '기준년월 시점 대출연체 과목수',
    '기준년월 시점 6개월내 대출연체 유지 과목수(연체대출금 상환 포함)',
]

# X, y 생성
X = df_건설[selected_features]
y = df_건설['기준일로부터 향후 1년내 부도, 기업회생, 90일이상 금융연체, 대지급 등 발생여부(신용정보원 기준). 1: 향후1년내 부도발생, 0: 향후1년내 부도미발생']


In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)


In [24]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [25]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)
model.fit(X_train_scaled, y_train)


RandomForestClassifier(class_weight='balanced', random_state=42)

In [26]:
y_pred = model.predict(X_test_scaled)


In [27]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred, digits=4))


              precision    recall  f1-score   support

           0     0.9867    0.9877    0.9872      3089
           1     0.0256    0.0238    0.0247        42

    accuracy                         0.9748      3131
   macro avg     0.5062    0.5058    0.5060      3131
weighted avg     0.9738    0.9748    0.9743      3131

